name: Build code base

on:
  push:
    branches:
      - refactorings
      - workflow
      - master
  pull_request:
    branches:
      - refactorings
      - workflow
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: JDK setup, Version 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clean and compile
        run: mvn -B clean compile --file JHotDraw/pom.xml
      - name: Run tests
        run: mvn -B test --file JHotDraw/pom.xml